Assign 2 :
Classify the email using the binary classification method. Email Spam detection has two 
states: a) Normal State – Not Spam, b) Abnormal State – Spam. Use K-Nearest Neighbors and 
Support Vector Machine for classification. Analyze their performance.

In [3]:

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("emails.csv")

In [5]:

df.drop(['Email No.'],axis=1,inplace=True)


In [6]:
X = df.drop(['Prediction'],axis = 1)
y = df['Prediction']
     


In [7]:


from sklearn.model_selection import train_test_split

from sklearn.preprocessing import scale
X = scale(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)
     


In [8]:


X_train
     


array([[ 0.03060621, -0.22951624, -0.2229717 , ..., -0.0562853 ,
        -0.32904848, -0.07097072],
       [-0.56544926, -0.64908256, -0.2938948 , ..., -0.0562853 ,
        -0.32904848, -0.07097072],
       [ 0.20090777, -0.12462466, -0.2229717 , ..., -0.0562853 ,
         0.39039297, -0.07097072],
       ...,
       [-0.56544926, -0.64908256, -0.2938948 , ..., -0.0562853 ,
        -0.32904848, -0.07097072],
       [-0.3951477 ,  0.50472481, -0.2938948 , ..., -0.0562853 ,
         0.75011369, -0.07097072],
       [-0.30999692, -0.64908256, -0.2938948 , ..., -0.0562853 ,
        -0.32904848, -0.07097072]])

In [9]:


y_train
     


1023    0
4587    0
4415    0
4863    1
4901    0
       ..
4426    0
466     0
3092    0
3772    1
860     1
Name: Prediction, Length: 3620, dtype: int64

In [10]:
#knn

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)


#printing prediction
print("Prediction",y_pred)

Prediction [0 0 1 ... 1 1 1]


C:\Users\banka\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [11]:

y_test

1566    0
1988    0
1235    1
3276    0
3438    0
       ..
3558    0
2298    0
1519    0
1740    0
1700    1
Name: Prediction, Length: 1552, dtype: int64

In [12]:


from sklearn import metrics
metrics.accuracy_score(y_test, y_pred)
     


0.8009020618556701

In [13]:
metrics.confusion_matrix(y_test, y_pred)

array([[804, 293],
       [ 16, 439]], dtype=int64)

In [14]:


from sklearn.svm import SVC
# cost C = 1
model = SVC(C = 1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
     


In [15]:


y_pred
     


array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [16]:
metrics.accuracy_score(y_test, y_pred)

0.9381443298969072

In [17]:


metrics.confusion_matrix(y_test, y_pred)
     


array([[1091,    6],
       [  90,  365]], dtype=int64)